substitutions:
  _PROJECT_ID: kp3p-prod
  _REGION: asia-south1
  _ARTIFACT_REPO: kp3p-repo
  _SERVICE: kp3p-intake
  _ADMIN_PUBLIC_URL: https://www.gastroai.in

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_ADMIN_PUBLIC_URL}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE}:latest'
      - '-f'
      - 'Patient-intake-form/Dockerfile'
      - './Patient-intake-form'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--project=${_PROJECT_ID}'
      - '--allow-unauthenticated'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE}'
